export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_REG = 'AUTH_REG'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const INIT_USER = 'INIT_USER'
export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_PHOTO = 'CHANGE_PHOTO'
