export const ADD_CARD_TO_COLLECTS = 'ADD_CARD_TO_COLLECT'
export const REMOVE_CARD_TO_COLLECT = 'REMOVE_CARD_TO_COLLECT'
export const INIT_COLLECTION = 'INIT_COLLECTION'
export const FILTER_COLLECTION = 'FILTER_COLLECTION'
